---
- hosts: all
  gather_facts: false
  vars:
    ssh_key: '/home/ec2-user/.ssh'
  tasks:
    - name: copy ssh key
      authorized_key:
        key: "{{ lookup('file', ssh_key) }}"
        user: root